# Generated by Django 4.1.3 on 2022-11-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(null=True, upload_to='../img/uploads'),
        ),
        migrations.AddField(
            model_name='cropcatalog',
            name='image',
            field=models.ImageField(null=True, upload_to='../img/uploads'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='../img/uploads'),
        ),
    ]
