# Generated by Django 4.1.3 on 2022-11-21 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_crop_name_alter_crop_placeoforigin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bankAccount',
            field=models.CharField(max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
