# Generated by Django 4.1.3 on 2022-11-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
