# Generated by Django 4.1.3 on 2022-11-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_dateofbirth_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dateOfBirth',
        ),
    ]
