# Generated by Django 4.1.3 on 2022-11-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='type',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='croptype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
