# Generated by Django 4.1.3 on 2022-11-21 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_suggestion_type_suggestion_croptype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='croptype',
            new_name='cropType',
        ),
    ]
